about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path("follow/", views.follow_index, name="follow_index"),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/', 
        views.post_edit, 
        name='post_edit'
    ),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('new', views.new_post, name='new_post'),
    path("<username>/<int:post_id>/comment", views.add_comment, name="add_comment"),
    path("<str:username>/follow/", views.profile_follow, name="profile_follow"), 
    path("<str:username>/unfollow/", views.profile_unfollow, name="profile_unfollow"),
]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

handler404 = 'posts.views.page_not_found'   # noqa
handler500 = 'posts.views.server_error'     # noqa

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

urlpatterns += staticfiles_urlpatterns()
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {
    'document_root': settings.MEDIA_ROOT,
}),]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Post(models.Model):
    text = models.TextField(verbose_name='Текст', help_text='Это поле обязательно, пожалуйста заполните его.')
    pub_date = models.DateTimeField('date published', auto_now_add=True, db_index=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='posts',
        null=True
    )
    group = models.ForeignKey(
        'Group', blank=True, null=True,
        related_name='posts', on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Это поле необязательно, но оно может помочь Вам найти единомышленников.'
    )

    image = models.ImageField(upload_to='posts/', blank=True, null=True)

    class Meta():
        ordering = ('-pub_date',)

    def __str__(self):
        sentence = (self.text[:15] + '..') if len(self.text) > 15 else self.text
        return sentence


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    created = models.DateTimeField('date published', auto_now_add=True)
    text = models.TextField(max_length=240)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    author = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='following')

posts/forms.py
from django.db.models import fields
from django.forms import ModelForm, Textarea, widgets

from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        widgets = {
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Напишите сюда что-нибудь...'
            })
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': Textarea(attrs={
                'rows': 3,
                'class': 'form-control',
                'placeholder': 'Расскажите, что думаете по этому поводу?',
            })
        }

posts/views.py
from typing import Text
from django.contrib.auth import get_user_model
from django.core import paginator
from django.core.paginator import Paginator
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django import forms
from django.urls import reverse
from django.views.decorators.cache import cache_page

from .models import Comment, Follow, Post, Group, User
from .forms import PostForm, CommentForm


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:12]
    group_posts = group.posts.all()
    paginator = Paginator(group_posts, 12)
    group_page_number = request.GET.get('page')
    page = paginator.get_page(group_page_number)
    return render(request, 'group.html', {'group': group, 'posts': posts, 'page': page, 'paginator': paginator})

def index(request):
    post_list = Post.objects.select_related('group').order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'index.html',
        {'page': page,
        'paginator': paginator,}
    )

def new_post(request):
    error = ''
    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES or None)
        if form.is_valid():
            post = form.save()
            post.author = request.user
            form.save()
            return redirect('index')
        else:
            error = 'Пожалуйста, повторите попытку'
    form = PostForm()
    data = {
        'form': form,
        'error': error,
    }
    return render(request, 'new_post.html', data)

def profile(request, username):
    author = get_object_or_404(User, username=username)
    author_post_list = author.posts.all()
    paginator = Paginator(author_post_list, 5)
    author_page_number = request.GET.get('page')
    auth_page = paginator.get_page(author_page_number)
    posts_count = Post.objects.filter(author=author).select_related('author').count()
    form = CommentForm(request.POST or None)
    folllowers_count = Follow.objects.filter(author__username=username).count()
    following_count = Follow.objects.filter(user__username=username).count()
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author
    ).exists()
    context = {
        'author': author,
        'page': auth_page,
        'paginator': paginator,
        'posts_count': posts_count,
        'form': form,
        'followers_count': folllowers_count,
        'following': following,
        'following_count': following_count,
    }
    return render(request, 'profile.html', context)

def post_view(request, username, post_id):
    author = User.objects.get(username=username)
    text = Post._meta.get_field('text')
    post = get_object_or_404(Post, id=post_id, author=author)
    posts_count = Post.objects.filter(author=author).select_related('author').count()
    comments = Comment.objects.filter(post=post_id).order_by('-created')
    form = CommentForm(request.POST or None)
    folllowers_count = Follow.objects.filter(author__username=username).count()
    following_count = Follow.objects.filter(user__username=username).count()
    context = {
        'text': text,
        'post': post,
        'posts_count': posts_count,
        'author': author,
        'post_id': post_id,
        'comments': comments,
        'form': form,
        'followers_count': folllowers_count,
        'following_count': following_count,
    }
    return render(request, 'post.html', context)

@login_required
def post_edit(request, username, post_id):
    profile = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, pk=post_id, author=profile)
    if request.user != profile:
        return redirect('post', username=username, post_id=post_id)
    form = PostForm(request.POST or None, files=request.FILES or None, instance=post)
    
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect("post", username=request.user.username, post_id=post_id)
    context = {
        'form': form,
        'post': post,
        'edited': True,
    }
    return render(
        request, 'new_post.html', context,
    ) 
 
def page_not_found(request, exception):
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=404
    )

def server_error(request):
    return render(request, "misc/500.html", status=500)

@login_required
def add_comment(request, username, post_id):
    post = Post.objects.get(pk=post_id)
    form = CommentForm(request.POST or None)
    if request.GET or not form.is_valid():
        return render(request, 'post.html', {'post': post, 'form': form})
    comment = form.save(commit=False)
    comment.author = request.user
    comment.post = post
    form.save()
    return redirect(reverse('post', kwargs={
        'username': username,
        'post_id': post_id
    }))

@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'post_list': post_list,
        'paginator': paginator,
        'page': page,
    }
    return render(request, "follow.html", context)

@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user and not Follow.objects.filter(
        user=request.user, author=author
    ).exists():
        Follow.objects.create(
            user=request.user, author=author
        )
        return redirect('profile', username=username)
    return redirect('profile', username=username)

@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('profile', username=username)

templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Yatube{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
    {% include 'nav.html' %}
    <main>
        <div class="container">
            {% block header %}<h1>Last Social Media You'll Ever Need
                 | Yatube</h1>{% endblock %}
            {% block content %}
            {% endblock %}
        </div>
    </main>
    {% include 'footer.html' %}
</body>

</html> 

templates/comments.html
{% load user_filters %}
{% if user.is_authenticated %}
<div class="card my-4">
    <form method="post" action="{% url 'add_comment' username=post.author post_id=post.id %}">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}
{% for item in comments %}
<div class="media card mb-4" style="margin-top: 3%;">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %}

templates/follow.html
{% extends "base.html" %} 
{% block title %}Записи Ваших любимых авторов{% endblock %}
{% block header %}{% endblock %}
{% block content %}
<div class="container">

    {% include "menu.html" with index=True %}

        <h1>Записи Ваших любимых авторов:</h1>

        {% load cache %}
                {% cache 20 index %}
                {% for post in post_list %}
                {% include "post_item.html" with post=post %}
                {% endfor %}
                {% endcache %}

        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
        {% endif %}

    </div>
{% endblock %} 

templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a>
        <a href="{% url 'about:tech' %}">Технологии</a>
    </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {% now 'Y' %}, все права защищены.</p>
  </footer> 

templates/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group.title }} | Yatube{% endblock %}
{% block header %}<h1>{{ group }}</h1>{% endblock %}
{% block content %}
<p>
    {{group.description|linebreaksbr}}
</p>
    {% for post in posts %}
        <h3>
            Автор: <a href="/{{ post.author }}">{{ post.author.get_full_name }}</a>, 
            Дата публикации: {{ post.pub_date|date:"d M Y" }}
        </h3>
        <p>{{ post.text|linebreaksbr }}</p>
        <hr>
    {% endfor %}

    {% include "paginator.html" %}

{% endblock %}

templates/index.html
{% extends "base.html" %} 
{% block title %}Последние обновления:{% endblock %}
{% block header %}{% endblock %}
{% block content %}
<div class="container">

    {% include "menu.html" with index=True %}

        <h1>Последние обновления на сайте:</h1>

        {% load cache %}
        {% cache 20 index %}
            {% for post in page %}
                {% include "post_item.html" with post=post %}
            {% endfor %}
        {% endcache %}
        
        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
        {% endif %}

    </div>
{% endblock %} 

templates/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}"
            style="border-radius: 7px; border: none; outline: none; background: white;
            box-shadow: -2px -2px 3px #e3f2fd, 2px 2px 3px #3333; margin: 15px 10px;">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if following %}active{% endif %}" href="/follow/"
            style="border-radius: 7px; border: none; outline: none; background: white;
            box-shadow: -2px -2px 3px #e3f2fd, 2px 2px 3px #3333; margin: 15px 10px;">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}

templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            Пользователь: {{ user.username }}
            <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a> |
            <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
            <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
            <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav> 

templates/new_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}{% if edited %}
Редактирование записи
{% else %}
Новая запись
{% endif %}{% endblock %}
{% block header %}
{% endblock %}
{% block content %}

<div class="row justify-content-center" style="margin-top: -2%;">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Новая запись</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% for field in error %}
                            {% autoescape off %}
                            {{ field|escape }}
                            {% endautoescape %}
                            {% endfor %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">
                                    {{ field|addclass:"form-control" }}
                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>                
                        </div>
                    {% endfor %}
                        <span>{{ error }}</span>
                    <div class="col-md-6 offset-md-4">
                        {% if edited %}
                            <button type="submit" class="btn btn-primary">
                                Сохранить
                            </button>
                        {% else %}
                            <button type="submit" class="btn btn-primary">
                                Добавить
                            </button>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %} 

templates/paginator.html
{% if page.has_other_pages %}
<nav>
  <ul class="pagination justify-content-center" style="margin-top: 2%;">

          {% if page.has_previous %}
     <li class="page-item">
       <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
     </li>
          {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
          {% endif %}
    
          
          {% for i in page.paginator.page_range %}
          {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
          {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
          {% endif %}
          {% endfor %}


          {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
          {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
          {% endif %}
  </ul>
</nav>
{% endif %} 

templates/post.html
{% extends "base.html" %}
{% block title %}Страница поста{% endblock %}
{% block header %}{% endblock %}
{% block content %}
<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                <div class="card">
                        <div class="card-body">
                                <div class="h2">
                                    {{ author.get_full_name }}
                                </div>
                                <div class="h3 text-muted">
                                     {{ author }}
                                </div>
                        </div>
                        <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                        Подписчиков: {{ followers_count }} <br />
                                        Подписан: {{ following_count }}
                                        </div>
                                </li>
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                            Записей: {{ posts_count }}
                                        </div>
                                </li>
                        </ul>
                </div>
        </div>

        <div class="col-md-9">

            <!-- Пост -->  
                <div class="card mb-3 mt-1 shadow-sm">
                        {% load thumbnail %}
                        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                        <img class="card-img" src="{{ im.url }}">
                        {% endthumbnail %}
                        <div class="card-body">
                                <p class="card-text">
                                        <a href="/{{ author }}/"><strong class="d-block text-gray-dark">@leo</strong></a>
                                        {{ post.text }}
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group ">
                                                {% if user.username == author.username %}
                                                <a class="btn btn-sm text-muted" href="/leo/36/edit" role="button">Редактировать</a>
                                                {% endif %}
                                        </div>
                                        <small class="text-muted">{{ post.pub_date|date:"d M Y" }}</small>
                                </div>
                        </div>
                </div>
                {% include 'comments.html' %}
     </div>
    </div>
</main> 
{% include "paginator.html" %}
{% endblock %}

templates/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

    <!-- Отображение картинки -->
    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}" />
    {% endthumbnail %}
    <!-- Отображение текста поста -->
    <div class="card-body">
      <p class="card-text">
        <!-- Ссылка на автора через @ -->
        <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}">
          <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
        </a>
        {{ post.text|linebreaksbr }}<hr>
      </p>
  
      <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
      {% if post.group %}
      <a class="card-link muted" href="{% url 'group_posts' post.group.slug %}">
        <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
      {% endif %}
      {% if post.comments.exists %}
      <div>
        Комментариев: {{ post.comments.count }}<hr>
      </div>
      {% endif %}
      <!-- Отображение ссылки на комментарии -->
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
        <div>
          <a class="btn btn-sm btn-primary" href="{% url 'post' post.author.username post.id %}" role="button">
            Добавить комментарий
          </a>
  
          <!-- Ссылка на редактирование поста для автора -->
          {% if user == post.author %}
          <a class="btn btn-sm btn-info" href="{% url 'post_edit' post.author.username post.id %}" role="button">
            Редактировать
          </a>
          {% endif %}
        </div>
        </div>
  
        <!-- Дата публикации поста -->
        <small class="text-muted">{{ post.pub_date }}</small>
      </div>
    </div>
  </div> 

templates/profile.html
{% extends "base.html" %}
{% block title %}Страница пользователя {{ author.username }}{% endblock %}
{% block header %}{% endblock %}
{% block content %}
{% load thumbnail %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-3 mb-3 mt-1">
      <div class="card">
      <div class="card-body">
        <div class="h2">
        {{ author.get_full_name }}
        </div>
        <div class="h3 text-muted">
        {{ author.username }}
        </div>
      </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
          {% if following %}
          <a class="btn btn-lg btn-light" 
            href="{% url 'profile_unfollow' author.username %}" role="button"> 
                Отписаться 
          </a> 
          {% else %}
          <a class="btn btn-lg btn-primary" 
            href="{% url 'profile_follow' author.username %}" role="button">
                Подписаться 
          </a>
          {% endif %}
          </li>
          <li class="list-group-item">
            <div class="h6 text-muted">
                Подписчиков: {{ followers_count }} <br />
                Подписан: {{ following_count }}
            </div>
          </li>
          <li class="list-group-item">
          <div class="h6 text-muted">
                Записей: {{ posts_count }}
          </div>
          </li>
        </ul>
        </div>
</div>
<div class="col-md-9">                
        {% for post in page %}
          {% include "post_item.html" with post=post %}
      {% endfor %}
    
         </div>
        </div>
        {% if page.has_other_pages %}
                      {% include "paginator.html" with items=page paginator=paginator%}
                  {% endif %}
    </main> 
{% endblock %}